name: llm_dart
description: A unified AI chat LLM interface library for Dart/Flutter
version: 0.0.1
homepage: https://github.com/Latias94/yumcha/tree/main/packages/llm_dart

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.8.0"

dependencies:
  dio: ^5.8.0
  meta: ^1.16.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.15
  mockito: ^5.4.0
